"""Qdrant vector store manager for RAG ingestion pipeline.

This module provides the VectorStoreManager class for managing Qdrant
collections, including collection creation, configuration, and validation.
Qdrant is used as the vector database for storing document embeddings with
metadata for semantic search and retrieval.

The VectorStoreManager handles:
- Idempotent collection creation with appropriate vector configurations
- Cosine distance metric (optimal for L2-normalized Qwen3 embeddings)
- Connection management to Qdrant server

Examples:
    Basic usage with default configuration:
        >>> manager = VectorStoreManager(
        ...     qdrant_url="http://crawl4r-vectors:6333",
        ...     collection_name="crawl4r"
        ... )
        >>> manager.ensure_collection()

    Custom vector dimensions:
        >>> manager = VectorStoreManager(
        ...     qdrant_url="http://crawl4r-vectors:6333",
        ...     collection_name="crawl4r",
        ...     dimensions=512
        ... )
        >>> manager.ensure_collection()

Notes:
    - All embeddings from Qwen3-Embedding-0.6B are L2-normalized (unit vectors)
    - Cosine distance is used for similarity search (appropriate for normalized
      vectors)
    - The ensure_collection() method is idempotent and safe to call multiple
      times
"""

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams


class VectorStoreManager:
    """Manages Qdrant vector store operations for document embeddings.

    This class provides methods for creating and configuring Qdrant collections
    with appropriate vector dimensions and distance metrics for semantic search.
    It serves as the primary interface for all Qdrant database operations in the
    RAG ingestion pipeline.

    The manager handles collection lifecycle operations and ensures proper
    configuration for storing embeddings generated by the TEI service using
    the Qwen3-Embedding-0.6B model.

    Attributes:
        qdrant_url: URL of the Qdrant server (e.g., "http://crawl4r-vectors:6333")
        collection_name: Name of the Qdrant collection to manage
        dimensions: Vector embedding dimensions (default 1024 for Qwen3)
        client: QdrantClient instance for database operations

    Examples:
        Create a manager with default settings:
            >>> manager = VectorStoreManager(
            ...     qdrant_url="http://crawl4r-vectors:6333",
            ...     collection_name="crawl4r"
            ... )
            >>> manager.ensure_collection()

        Use custom dimensions for embeddings:
            >>> manager = VectorStoreManager(
            ...     qdrant_url="http://crawl4r-vectors:6333",
            ...     collection_name="crawl4r",
            ...     dimensions=512
            ... )
            >>> manager.ensure_collection()

    Notes:
        - The default dimensions (1024) match Qwen3-Embedding-0.6B output
        - Cosine distance is used because Qwen3 produces L2-normalized vectors
        - All operations are designed to be idempotent where possible
    """

    def __init__(
        self,
        qdrant_url: str,
        collection_name: str,
        dimensions: int = 1024,
    ) -> None:
        """Initialize VectorStoreManager with Qdrant connection.

        Creates a connection to the Qdrant server and stores configuration
        parameters for collection management. The connection is established
        immediately upon initialization.

        Args:
            qdrant_url: URL of the Qdrant server including protocol and port.
                Examples: "http://localhost:6333", "http://crawl4r-vectors:6333"
            collection_name: Name of the collection to manage. This should match
                the collection name configured in the application settings.
            dimensions: Vector embedding dimensions. Must match the dimension
                size of embeddings produced by your embedding model. Default is
                1024 for Qwen3-Embedding-0.6B at full dimensions.

        Raises:
            ValueError: If qdrant_url is empty or malformed.
            ConnectionError: If unable to connect to Qdrant server.

        Examples:
            Production configuration:
                >>> manager = VectorStoreManager(
                ...     qdrant_url="http://crawl4r-vectors:6333",
                ...     collection_name="crawl4r"
                ... )

            Development with custom dimensions:
                >>> manager = VectorStoreManager(
                ...     qdrant_url="http://localhost:6333",
                ...     collection_name="test-collection",
                ...     dimensions=512
                ... )

        Notes:
            - The QdrantClient connection is created synchronously
            - No validation is performed on the URL format (delegated to client)
            - The dimensions value is stored but only used when creating
              collections
        """
        self.qdrant_url = qdrant_url
        self.collection_name = collection_name
        self.dimensions = dimensions
        self.client = QdrantClient(url=qdrant_url)

    def ensure_collection(self) -> None:
        """Create collection if it does not exist (idempotent operation).

        Checks if the collection already exists in Qdrant. If not, creates
        a new collection with the configured vector dimensions and cosine
        distance metric. This method is idempotent and safe to call multiple
        times without side effects.

        The collection is configured with:
        - Vector size matching self.dimensions (default 1024 for Qwen3)
        - Cosine distance metric (optimal for L2-normalized embeddings)

        Returns:
            None. The method performs the operation silently and does not
            return a value.

        Raises:
            ConnectionError: If unable to communicate with Qdrant server.
            ValueError: If collection creation fails due to invalid parameters.

        Examples:
            First call creates the collection:
                >>> manager = VectorStoreManager(
                ...     qdrant_url="http://crawl4r-vectors:6333",
                ...     collection_name="crawl4r"
                ... )
                >>> manager.ensure_collection()  # Creates collection

            Subsequent calls are no-ops:
                >>> manager.ensure_collection()  # Skips (already exists)
                >>> manager.ensure_collection()  # Skips (already exists)

        Notes:
            - Cosine distance is used because Qwen3-Embedding-0.6B produces
              L2-normalized vectors (unit vectors with norm = 1.0)
            - The method does not verify existing collection configuration.
              If a collection exists with different parameters, it will not
              be modified
            - Collection creation is synchronous and blocks until complete
        """
        # Check if collection already exists to avoid redundant creation
        if self.client.collection_exists(self.collection_name):
            return

        # Create collection with vector configuration for Qwen3 embeddings
        # - size: Vector dimension count (must match embedding model output)
        # - distance: COSINE for normalized vectors (as opposed to EUCLID or DOT)
        self.client.create_collection(
            collection_name=self.collection_name,
            vectors_config=VectorParams(
                size=self.dimensions, distance=Distance.COSINE
            ),
        )
